apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytoumi-playground
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: yahyatoumi/yahya-toumi-cicd-app:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: ytoumi-playground
spec:
  selector:
    app: myapp
  ports:
  - port: 8888
    targetPort: 8888
  type: LoadBalancer
