apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytoumi-playground
  namespace: dev
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: yahyatoumi/yahya-toumi-cicd-app:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ytoumi-playground
  namespace: dev
spec:
  selector:
    app: myapp
  ports:
    - port: 8888
      targetPort: 80
  type: LoadBalancer
  externalIPs:
    - 127.0.0.1 
